cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('adjust/<item_id>/', views.update_cart, name='update_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

minion_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('favorites/', include('favorites.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'minion_shop.views.handler404'

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<product_id>', views.product_detail, name='product_detail'),
    path('positive_reviews/<product_id>', views.positive_reviews_view, name='positive_reviews'),
    path('negative_reviews/<product_id>', views.negative_reviews_view, name='negative_reviews'),
    path('add_favorites/<int:product_id>', views.add_favorite, name='add_favorite'),
    path('remove_favorites/<product_id>', views.remove_favorite, name='remove_favorite'),
    path('edit_positive_review/<positive_review_id>', views.edit_positive_review, name='edit_positive_review'),
    path('delete_positive_review/<positive_review_id>', views.delete_positive_review, name='delete_positive_review'),
    path('edit_negative_review/<negative_review_id>', views.edit_negative_review, name='edit_negative_review'),
    path('delete_negative_review/<negative_review_id>', views.delete_negative_review, name='delete_negative_review'),
]

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum

from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=False, related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    order_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    original_cart = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False, blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added.
        """
        self.order_total = self.lineitems.aggregate(Sum('lineitem_total'))['lineitem_total__sum'] or 0
        self.grand_total = self.order_total
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False, on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(Product, null=False, blank=False, on_delete=models.CASCADE)
    product_tier = models.CharField(max_length=2, null=True, blank=True)  # 1-11
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2, null=False, blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    has_tiers = models.BooleanField(default=False, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    favorites = models.ManyToManyField(
        User, related_name='product_favorites', blank=True)

    def __str__(self):
        return self.name


class PositiveReview(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                related_name="positive_reviews")
    name = models.CharField(null=True, blank=True, max_length=60)
    positive_review = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Product {self.positive_review} by {self.name}"


class NegativeReview(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                related_name="negative_reviews")
    name = models.CharField(null=True, blank=True, max_length=60)
    negative_review = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Product {self.negative_review} by {self.name}"

products/forms.py
from django import forms
from .models import PositiveReview, NegativeReview


class PositiveReviewForm(forms.ModelForm):
    class Meta:
        model = PositiveReview
        fields = ('positive_review', 'name',)


class NegativeReviewForm(forms.ModelForm):
    class Meta:
        model = NegativeReview
        fields = ('negative_review', 'name',)

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth import get_user
from django.db.models import Q
from django.db.models.functions import Lower
from .models import Product, Category, PositiveReview, NegativeReview
from .forms import PositiveReviewForm, NegativeReviewForm
from favorites.models import Favorite

# Create your views here.


def all_products(request):
    """ A view to show all products, including sorting and search queries """

    products = Product.objects.all()

    query = None
    categories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "You didn't enter any search criteria!")
                return redirect(reverse('products'))

            queries = Q(name__icontains=query) | Q(description__icontains=query)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ A view to show individual product details """

    product = get_object_or_404(Product, pk=product_id)
    favorited = False

    if request.user in product.favorites.all():
        favorited = True

    template = 'products/product_detail.html'
    context = {
        'product': product,
        'favorited': favorited,
    }

    return render(request, template, context)


def positive_reviews_view(request, product_id):
    """ A view to show individual product positive reviews """

    product = get_object_or_404(Product, pk=product_id)
    positive_reviews = product.positive_reviews.order_by("-created_on")
    # Get the currently logged-in User.
    user = get_user(request)
    # Provide User as initial data to the form
    positive_review_form = PositiveReviewForm(initial={'name': user})

    if request.method == 'POST':
        positive_review_form = PositiveReviewForm(data=request.POST)
        if positive_review_form.is_valid():
            positive_review_form.instance.name = request.user.username
            positive_review = positive_review_form.save(commit=False)
            positive_review.product = product
            positive_review.save()
        else:
            messages.error(request, "Your Positive Review was not submitted")

    template = 'products/positive_reviews.html'
    context = {
        'product': product,
        "positive_reviews": positive_reviews,
        "positive_review_form": positive_review_form,
    }

    return render(request, template, context)


def negative_reviews_view(request, product_id):
    """ A view to show individual product negative reviews """

    product = get_object_or_404(Product, pk=product_id)
    negative_reviews = product.negative_reviews.order_by("-created_on")
    # Get the currently logged-in User.
    user = get_user(request)
    # Provide User as initial data to the form
    negative_review_form = NegativeReviewForm(initial={'name': user})

    if request.method == 'POST':
        negative_review_form = NegativeReviewForm(data=request.POST)
        if negative_review_form.is_valid():
            negative_review_form.instance.name = request.user.username
            negative_review = negative_review_form.save(commit=False)
            negative_review.product = product
            negative_review.save()
        else:
            messages.error(request, "Your negative Review was not submitted")

    template = 'products/negative_reviews.html'
    context = {
        'product': product,
        "negative_reviews": negative_reviews,
        "negative_review_form": negative_review_form,
    }

    return render(request, template, context)


def add_favorite(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    Favorite.objects.get_or_create(product_id=product_id, user=request.user)
    product.favorites.add(request.user)

    return redirect('product_detail', product_id)


def remove_favorite(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    favorite = Favorite.objects.get(product_id=product_id, user=request.user)
    favorite.delete()
    product.favorites.remove(request.user)

    return redirect('product_detail', product_id)


def edit_positive_review(request, positive_review_id):

    positive_review = get_object_or_404(PositiveReview, id=positive_review_id)

    if request.method == 'POST':
        existing_positive_review = PositiveReviewForm(request.POST, instance=positive_review)
        if existing_positive_review.is_valid():
            existing_positive_review.instance.name = request.user.username
            existing_positive_review.save()
            messages.success(request, "Your Positive Review Was Updated")
            return redirect(reverse('products'))
        else:
            messages.error(request, "Your Positive Review Was Not Updated")
    existing_positive_review = PositiveReviewForm(instance=positive_review)

    context = {
        'existing_positive_review': existing_positive_review,
        "positive_review": positive_review,
    }
    return render(request, 'products/edit_positive_review.html', context)


def delete_positive_review(request, positive_review_id):

    positive_review = get_object_or_404(PositiveReview, id=positive_review_id)
    positive_review.delete()
    messages.success(request, "Your Positive Review Was Deleted Successfully")
    return redirect('products')


def edit_negative_review(request, negative_review_id):

    negative_review = get_object_or_404(NegativeReview, id=negative_review_id)

    if request.method == 'POST':
        existing_negative_review = NegativeReviewForm(request.POST, instance=negative_review)
        if existing_negative_review.is_valid():
            existing_negative_review.instance.name = request.user.username
            existing_negative_review.save()
            messages.success(request, "Your Negative Review Was Updated")
            return redirect(reverse('products'))
        else:
            messages.error(request, "Your Negative Review Was Not Updated")
    existing_negative_review = NegativeReviewForm(instance=negative_review)

    context = {
        'existing_negative_review': existing_negative_review,
        "negative_review": negative_review,
    }
    return render(request, 'products/edit_negative_review.html', context)


def delete_negative_review(request, negative_review_id):

    negative_review = get_object_or_404(NegativeReview, id=negative_review_id)
    negative_review.delete()
    messages.success(request, "Your Negative Review Was Deleted Successfully")
    return redirect('products')

products/templates/products/edit_negative_review.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
{% if user.is_authenticated %}
<div class="container">
    <div class="row">
        <div class="col-sm">
            <div class="card-body">
                <h3>Edit Negative Review:</h3>
                <form method="post" style="margin-top: 1.3em;">
                    {% csrf_token %}
                    <div>
                        {{ existing_negative_review.negative_review | as_crispy_field }}
                    </div>
                    <button type="submit" class="btn btn-blue btn-signup btn-lg text-better-white">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="container-fluid">
    <div class="row">
        <div class="col text-center mt-3">
            <h2 class="logo-font">Please Log In/Register To Go Beyond The Home Page</h2>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

products/templates/products/edit_positive_review.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
{% if user.is_authenticated %}
<div class="container">
    <div class="row">
        <div class="col-sm">
            <div class="card-body">
                <h3>Edit Positive Review:</h3>
                <form method="post" style="margin-top: 1.3em;">
                    {% csrf_token %}
                    <div>
                        {{ existing_positive_review.positive_review | as_crispy_field }}
                    </div>
                    <button type="submit" class="btn btn-blue btn-signup btn-lg text-better-white">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="container-fluid">
    <div class="row">
        <div class="col text-center mt-3">
            <h2 class="logo-font">Please Log In/Register To Go Beyond The Home Page</h2>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

products/templates/products/negative_reviews.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
{% if request.user.is_authenticated %}
<div class="container">
    <div class="row">
        <div class="col-sm">
            <div class="image-container my-5">
                {% if product.image %}
                <a href="{{ product.image.url }}" target="_blank">
                    <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                </a>
                {% else %}
                <a href="">
                    <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                </a>
                {% endif %}
            </div>
        </div>
        <div class="col-sm">
            <div class="card-body">
                {% if user.is_authenticated %}

                <h3>Leave A Negative Review:</h3>
                <form method="post" style="margin-top: 1.3em;">
                    {% csrf_token %}
                    <div>
                        {{ negative_review_form.negative_review | as_crispy_field }}
                    </div>
                    <button type="submit" class="btn btn-blue btn-signup btn-lg text-better-white">Submit</button>
                </form>
                {% endif %}
            </div>
        </div>
        <div class="col-sm">
            <div class="card-body">
                <h3>Negative Reviews:</h3>
                <!-- We want a for loop inside the empty control tags to iterate through each negative review in negative_reviews -->
                {% for negative_review in negative_reviews %}
                <div class="comments review-box" style="padding: 10px;">
                    <p class="font-weight-bold">
                        <!-- The commenter's name goes here. Check the model if you're not sure what that is -->
                        {{ negative_review.name }}
                        <span class=" text-muted font-weight-normal">
                            wrote:
                        </span>
                    </p>
                    <!-- The body of the comment goes before the | -->
                    {{ negative_review.negative_review | linebreaks }}
                </div>
                {% if negative_review.name == request.user.username %}
                <a href="{% url 'edit_negative_review' negative_review.id %}" class="card-link">Edit</a>
                <a href="{% url 'delete_negative_review' negative_review.id %}" class="card-link text-danger">delete</a>
                <!-- Our for loop ends here -->
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="container-fluid">
    <div class="row">
        <div class="col text-center mt-3">
            <h2 class="logo-font">Please Log In/Register To Go Beyond The Home Page</h2>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

products/templates/products/positive_reviews.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
{% if request.user.is_authenticated %}
<div class="container">
    <div class="row">
        <div class="col-sm">
            <div class="image-container my-5">
                {% if product.image %}
                <a href="{{ product.image.url }}" target="_blank">
                    <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                </a>
                {% else %}
                <a href="">
                    <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                </a>
                {% endif %}
            </div>
        </div>
        <div class="col-sm">
            <div class="card-body">
                {% if user.is_authenticated %}

                <h3>Leave A Positive Review:</h3>
                <form method="post" style="margin-top: 1.3em;">
                    {% csrf_token %}
                    <div>
                        {{ positive_review_form.positive_review | as_crispy_field }}
                    </div>
                    <button type="submit" class="btn btn-blue btn-signup btn-lg text-better-white">Submit</button>
                </form>
                {% endif %}
            </div>
        </div>
        <div class="col-sm">
            <div class="card-body">
                <h3>Positive Reviews:</h3>
                <!-- We want a for loop inside the empty control tags to iterate through each positive review in positive_reviews -->
                {% for positive_review in positive_reviews %}
                <div class="comments review-box" style="padding: 10px;">
                    <p class="font-weight-bold">
                        <!-- The commenter's name goes here. Check the model if you're not sure what that is -->
                        {{ positive_review.name }}
                        <span class=" text-muted font-weight-normal">
                            wrote:
                        </span>
                    </p>
                    <!-- The body of the comment goes before the | -->
                    {{ positive_review.positive_review | linebreaks }}
                </div>
                {% if positive_review.name == request.user.username %}
                <a href="{% url 'edit_positive_review' positive_review.id %}" class="card-link">Edit</a>
                <a href="{% url 'delete_positive_review' positive_review.id %}" class="card-link text-danger">delete</a>
                <!-- Our for loop ends here -->
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="container-fluid">
    <div class="row">
        <div class="col text-center mt-3">
            <h2 class="logo-font">Please Log In/Register To Go Beyond The Home Page</h2>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'product/css/product.css' %}">
{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
{% if request.user.is_authenticated %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
            <div class="image-container my-5">
                {% if product.image %}
                <a href="{{ product.image.url }}" target="_blank">
                    <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                </a>
                {% else %}
                <a href="">
                    <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                </a>
                {% endif %}
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
            <div class="product-details-container mb-5 mt-md-5">
                <p class="mb-0">{{ product.name }}</p>
                {% if favorited %}
                <a href="{% url 'remove_favorite' product.id %}">
                    <small class="text-danger">Favorite</small>
                </a>
                {% else %}
                <a href="{% url 'add_favorite' product_id=product.pk %}">
                    <small class="text-muted">Favorite</small>
                </a>
                {% endif %}
                <p class="lead mb-0 text-left font-weight-bold">${{ product.price }}</p>
                {% if product.category %}
                <p class="small mt-1 mb-0">
                    <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name }}">
                        <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                    </a>
                </p>
                {% endif %}
                <p class="mt-3">{{ product.description }}</p>
                <form class="form" action="{% url 'add_to_cart' product.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-row">
                        {% with product.has_tiers as t %}
                        {% if t %}
                        <div class="col-12">
                            <p><strong>Tier:</strong></p>
                            <select class="form-control rounded-0 w-50" name="product_tier" id='id_product_tier'>
                                <option value="1" selected>1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                                <option value="9">9</option>
                                <option value="10">10</option>
                                <option value="11">11</option>
                            </select>
                        </div>
                        {% endif %}
                        <div class="col-12">
                            <p class="mt-3"><strong>Quantity:</strong></p>
                            <div class="form-group w-50">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <button
                                            class="decrement-qty btn btn-red rounded-0 decrement-qty_{{ product.id }} text-better-white btn-black-border"
                                            data-item_id="{{ product.id }}">
                                            <span class="icon">
                                                <i class="fas fa-minus"></i>
                                            </span>
                                        </button>
                                    </div>
                                    <input class="form-control qty_input id_qty_{{ product.id }} btn-black-border"
                                        type="number" name="quantity" value="1" min="1" max="39"
                                        data-item_id="{{ product.id }}">
                                    <div class="input-group-append">
                                        <button
                                            class="increment-qty btn btn-green rounded-0 increment-qty_{{ product.id }} text-better-white btn-black-border"
                                            data-item_id="{{ product.id }}">
                                            <span class="icon">
                                                <i class="fas fa-plus"></i>
                                            </span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col{% if t %}-12 mt-2{% endif %}">
                            <a href="{% url 'products' %}" class="btn btn-black-border rounded-0 mt-5">
                                <span class="icon">
                                    <i class="fas fa-chevron-left"></i>
                                </span>
                                <span class="text-uppercase">Keep Shopping</span>
                            </a>
                            <input type="submit"
                                class="btn btn-green btn-black-border rounded-0 text-uppercase mt-5 text-better-white"
                                value="Add to Bag">
                        </div>
                        <div class="row w-100">
                            <a href="{% url 'positive_reviews' product.id %}"
                                class="btn btn-green rounded-0 btn-black-border btn-lg" style="margin-top: 1.5em;">
                                <span class="text-uppercase text-better-white">positive reviews</span>
                            </a>
                            <a href="{% url 'negative_reviews' product.id %}"
                                class="btn btn-red rounded-0 btn-black-border btn-lg" style="margin-top: 1.5em;">
                                <span class="text-uppercase text-better-white">negative reviews</span>
                            </a>
                        </div>
                        <input type="hidden" name="redirect_url" value="{{ request.path }}">


                        {% endwith %}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="container-fluid">
    <div class="row">
        <div class="col text-center mt-3">
            <h2 class="logo-font">Please Log In/Register To Go Beyond The Home Page</h2>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}